### PR TITLE
fix: New table widget migration to sanitize primaryColumn, columnOrder and binding paths

### LINKED ISSUE #6897: [Bug] TypeError: t.filter is not a function
Sentry Issue: [APPSMITH-12J](https://sentry.io/organizations/appsmith/issues/2602849328/?referrer=github_integration)

```
TypeError: t.filter is not a function
  at None (widgets/BaseWidget.tsx:185:14)
  at Array.reduce (<anonymous>)
  at apply (widgets/BaseWidget.tsx:183:38)
  at showWidgetName (widgets/BaseWidget.tsx:225:30)
  at getWidgetView (widgets/BaseWidget.tsx:316:26)
...
(41 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by ashit-rath**
## Description
This PR adds a new migration to mitigate the issue due to bad merge in CE and EE which resulted into inconsistent table widget dsl where the the table keys were not sanitized properly.

Fixes #6897

1. Checkout to the `master` branch
2. Create a new application
3. Add a table widget
4. Add some datasource (eg. users)
5. Open table widget property pane and add the following to the data property 
   ```
    {{users.data.concat({ "'new header": 100})}}
   ```
6. Export the application
7. Checkout to release branch
8. Import the application

After importing the application should ideally crash.

#### Reason for the crash - 
Background - Due to some recent bad merge from release to master, certain pieces of code got reverted. CE master has the bad code but release has the appropriate changes.

Now when the application is exported while being on the `master` branch, the bad dsl (due to bad code) goes out and the dsl is on the latest version (migration wise).  When this code is imported while being on the `release` branch, the code sees that the dsl is on the latest migration version, it does not try to fix the issue present on the dsl (even though previous migration can somewhat fix the dsl). The bad un-sanitized DSL goes in and crashes the application.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Test coverage results :test_tube:
<details><summary>:green_circle: Total coverage has increased</summary>

    // Code coverage diff between base branch:release and head branch: fix/6897-table-migration-sanitize-keys 
Status | File | % Stmts | % Branch | % Funcs | % Lines 
 -----|-----|---------|----------|---------|------ 
 :green_circle: | total | 54.46 **(0.05)** | 36.32 **(0.06)** | 33.6 **(0.05)** | 55.01 **(0.05)**
 :green_circle: | app/client/src/utils/DSLMigrations.ts | 74.87 **(0.14)** | 66.27 **(-0.06)** | 69.77 **(0)** | 74.46 **(0.14)**
 :green_circle: | app/client/src/utils/helpers.tsx | 65.15 **(1.28)** | 39.18 **(1.29)** | 46.88 **(1.72)** | 62.18 **(1.25)**
 :red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**
 :green_circle: | app/client/src/utils/migrations/TableWidget.ts | 81.14 **(5.96)** | 72.78 **(2.33)** | 90.91 **(7.58)** | 83.87 **(5.13)**</details>

### CODE REVIEW

File: app/client/src/utils/migrations/TableWidget.ts [hunk 1]
```diff
@@ -310,3 +310,87 @@ export const migrateTablePrimaryColumnsComputedValue = (
...
+
+      // Sanitizes [ "id", "name", $$$random_header ]
+      // to [ "id", "name", _random_header ]
+      child.columnOrder = (child.columnOrder || []).map((co: string) =>
+        removeSpecialChars(co, 200),
+      );
+
+      // Sanitizes [ {key: primaryColumns.$$$random_header.computedValue }]
+      // to [ {key: primaryColumns._random_header.computedValue }]
+      child.dynamicBindingPathList = (child.dynamicBindingPathList || []).map(
```
Comment (ashit-rath) [inline app/client/src/utils/migrations/TableWidget.ts:371]: I am bit concerned about this block of code. If the DSL runs from old migration i.e before 27 then the `primaryColumn` keys would already be sanitized and `primaryColumnKeyTuples` wouldn't have any entries
Check -> https://github.com/appsmithorg/appsmith/pull/7037/files#diff-3381042113ebd91605a3f90f24317750e0433d3408fe8717b036ae612c8c7f27R342

Basically for `primaryColumns.$$$random_header.computedValue` we need to sanitize `$$$random_header`.  We cannot split the string using `split('.')` and apply sanitization on the index[1] as the the bad key could be something like `.random_header` and that would lead to `primaryColumns..random_header.computedValue` and would break the code.

We could grab everything in between `primaryColumns` and `computedValue` and sanitize but I'm not sure if the path would always have the same pattern or may change.

@riodeuno Please advice.

**Review by somangshu — APPROVED** [review]
Approving to run the tests

**Comment by ashit-rath** [comment]
Note: This issue can now only be reproduced on master on commit: `6754cc01d2e54db072cc8f181895a9775aa09f5e`. Latest master has code discrepancy fixes.

File: app/client/src/utils/migrations/TableWidget.ts (hunk 1 above)
Comment (riodeuno) [reply app/client/src/utils/migrations/TableWidget.ts:371]: @ashit-rath You're right, when sanitisations were happening with `\W+`, we could be certain that `primaryColumns..random_header.computedvalue` could not be the case. However, now that we've used `/\s+` we might see these scenarios as we've seen users using keys in their data like `Employee.id` which would make this `primaryColumns.Employee.id.computedValue`. 

For now, we can assume that `primaryColumns.xxxx.yyyy`, where xxxx is the pattern which we will need to sanitize.

File: app/client/src/utils/migrations/TableWidget.test.ts [hunk 2]
```diff
@@ -1203,3 +1204,256 @@ describe("Table Widget Property Pane Upgrade", () => {
...
+          bottomRow: 53,
+          parentRowSpace: 10,
+          type: "TABLE_WIDGET",
+          parentColumnSpace: 14.62421875,
+          dynamicTriggerPathList: [],
+          dynamicBindingPathList: [
+            { key: "tableData" },
+            { key: "primaryColumns.id.computedValue" },
+            { key: "primaryColumns.name.computedValue" },
+            { key: "primaryColumns.'random_header.computedValue" },
```
Comment (riodeuno) [inline app/client/src/utils/migrations/TableWidget.test.ts:1247]: Let's add another unit test to test the `primaryColumns.Employee.id.computedValue` scenario.

**Review by riodeuno — CHANGES_REQUESTED** [review]
Nice work considering all the scenarios. Please add that one more test case. The rest looks good.

**Review by somangshu — DISMISSED** [review]
Approving for the tests to run

**Comment by somangshu** [comment]
@riodeuno please look into this, This should get merged into release soon.

**Review by riodeuno — APPROVED** [review]

**Review by somangshu — DISMISSED** [review]

**Comment by ashit-rath** [comment]
@vivekverma2312 You can now test the DP

File: app/client/src/utils/WidgetPropsUtils.tsx [hunk 3]
```diff
@@ -50,1101 +30,6 @@ type Rect = {
 
 const defaultDSL = defaultTemplate;
 
-const updateContainers = (dsl: ContainerWidgetProps<WidgetProps>) => {
```
Comment (riodeuno) [inline app/client/src/utils/WidgetPropsUtils.tsx]: This diff should not show up here, as the `release` branch already has these changes. Any idea about what happened here?

File: app/client/src/utils/helpers.test.ts [hunk 4]
```diff
@@ -84,3 +84,23 @@ describe("flattenObject test", () => {
     );
   });
 });
+
+describe("#getSubstringBetweenTwoWords", () => {
```
Comment (riodeuno) [inline app/client/src/utils/helpers.test.ts:88]: Beautiful! This is how we should validate our functions.

File: app/client/src/utils/helpers.tsx [hunk 5]
```diff
@@ -291,6 +291,25 @@ export const isString = (str: any) => {
   return typeof str === "string" || str instanceof String;
 };
 
+/**
+ * Returns substring between two set of strings
+ * eg ->
```
Comment (riodeuno) [inline app/client/src/utils/helpers.tsx:296]: Another nice detail. These function comments will help in the long run.

File: app/client/src/utils/migrations/TableWidget.ts [hunk 6]
```diff
@@ -304,3 +305,85 @@ export const migrateTablePrimaryColumnsComputedValue = (
   });
   return currentDSL;
 };
+
+/**
+ * This migration sanitizes the following properties -
+ * primaryColumns object key, for the value of each key - id, computedValue are sanitized
+ * columnOrder
```
Comment (riodeuno) [inline app/client/src/utils/migrations/TableWidget.ts:312]: 💯

**Review by riodeuno — APPROVED** [review]

**Comment by vivekverma2312** [comment]
Tested on Deploy Preview and working fine.
